services:
  vigilbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vigilbot
    restart: unless-stopped
    ports:
      - "8000:8000"  # FastAPI port
      - "8080:8080"  # Next.js frontend port
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - TZ=UTC
      - API_PORT=8000
      - FRONTEND_PORT=8080
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws