version: '3'

services:
  # Backend API service
  vigilbot-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: vigilbot-api
    restart: unless-stopped
    ports:
      - "1337:8000"  # FastAPI port
    volumes:
      - /mnt/user/appdata/vigilbot/config:/app/config
      - /mnt/user/appdata/vigilbot/logs:/app/logs
      - /mnt/user/appdata/vigilbot/temp:/app/temp
      - /mnt/user/appdata/vigilbot/.env:/app/.env  # Mount .env directly into the container
    environment:
      - TZ=UTC
      - PUID=99
      - PGID=100
      - API_PORT=8000
    networks:
      - vigilbot-network

  # Frontend service
  vigilbot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: vigilbot-frontend
    restart: unless-stopped
    ports:
      - "1338:3000"  # Next.js frontend port
    environment:
      - TZ=UTC
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://vigilbot-api:8000
      - NEXT_PUBLIC_WS_URL=ws://vigilbot-api:8000/ws
    networks:
      - vigilbot-network
    depends_on:
      - vigilbot-api

networks:
  vigilbot-network:
    driver: bridge